#!/usr/bin/env node
// Exports DESIGN.md frontmatter tokens to CSS custom properties (design/tokens.css).
//   node tokens-css.mjs [--project <dir>] [--out design/tokens.css]
// Reads the Stitch-style YAML subset: scalar maps plus one nesting level (typography roles, components).
import { existsSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, resolve, dirname } from "node:path";

const args = process.argv.slice(2);
const opt = (n, d) => { const i = args.indexOf(n); return i >= 0 ? args[i + 1] : d; };
const project = resolve(opt("--project", process.cwd()));
const out = resolve(project, opt("--out", "design/tokens.css"));
const md = existsSync(join(project, "DESIGN.md")) ? readFileSync(join(project, "DESIGN.md"), "utf8") : null;
if (!md) { console.error("DESIGN.md not found"); process.exit(1); }
let lines = md.split(/\r?\n/);
while (lines.length && (lines[0].trim() === "" || /^<!--.*-->\s*$/.test(lines[0].trim()))) lines.shift();
if (!lines.length || lines[0].trim() !== "---") { console.error("DESIGN.md has no frontmatter"); process.exit(1); }
const end = lines.findIndex((l, i) => i > 0 && l.trim() === "---");
const yaml = lines.slice(1, end);

// tiny YAML subset: key: value | key: (map) with 2-space indents, up to 2 levels
const root = {}; const stack = [{ indent: -1, obj: root }];
for (const raw of yaml) {
  if (!raw.trim() || raw.trim().startsWith("#")) continue;
  const indent = raw.match(/^ */)[0].length; const line = raw.trim();
  const m = line.match(/^([^:]+):\s*(.*)$/); if (!m) continue;
  const key = m[1].trim(); let val = m[2].trim();
  while (stack.length && stack[stack.length - 1].indent >= indent) stack.pop();
  const parent = stack[stack.length - 1].obj;
  if (val === "") { parent[key] = {}; stack.push({ indent, obj: parent[key] }); }
  else { if (/^["'].*["']$/.test(val)) val = val.slice(1, -1); parent[key] = val; }
}
const slug = (s) => String(s).toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
const ref = (v) => typeof v === "string" ? v.replace(/\{([a-z]+)\.([^}]+)\}/gi, (_, g, k) => `var(--${g === "colors" ? "color" : g === "rounded" ? "radius" : g === "spacing" ? "space" : g}-${slug(k)})`) : v;
const css = [];
css.push(`/* generated by designli-design from DESIGN.md frontmatter; edit DESIGN.md, then re-run tokens-css.mjs */`);
css.push(`:root {`);
for (const [k, v] of Object.entries(root.colors || {})) css.push(`  --color-${slug(k)}: ${v};`);
for (const [role, t] of Object.entries(root.typography || {})) {
  if (typeof t !== "object") continue;
  if (t.fontFamily) css.push(`  --font-${slug(role)}-family: ${/[ ,]/.test(t.fontFamily) && !/^["']/.test(t.fontFamily) ? `"${t.fontFamily.split(",")[0].trim()}"${t.fontFamily.includes(",") ? "," + t.fontFamily.split(",").slice(1).join(",") : ""}` : t.fontFamily};`);
  if (t.fontSize) css.push(`  --font-${slug(role)}-size: ${t.fontSize};`);
  if (t.fontWeight) css.push(`  --font-${slug(role)}-weight: ${t.fontWeight};`);
  if (t.lineHeight) css.push(`  --font-${slug(role)}-line-height: ${t.lineHeight};`);
  if (t.letterSpacing) css.push(`  --font-${slug(role)}-letter-spacing: ${t.letterSpacing};`);
}
for (const [k, v] of Object.entries(root.rounded || {})) css.push(`  --radius-${slug(k)}: ${v};`);
for (const [k, v] of Object.entries(root.spacing || {})) css.push(`  --space-${slug(k)}: ${v};`);
css.push(`}`);
const comps = Object.entries(root.components || {});
if (comps.length) {
  css.push(``, `/* component recipes (token references resolved to custom properties) */`);
  for (const [name, props] of comps) {
    if (typeof props !== "object") continue;
    css.push(`.ds-${slug(name)} {`);
    const map = { backgroundColor: "background-color", textColor: "color", rounded: "border-radius", padding: "padding", height: "height", width: "width", size: "font-size" };
    for (const [p, v] of Object.entries(props)) if (map[p]) css.push(`  ${map[p]}: ${ref(v)};`);
    if (props.typography) css.push(`  font: var(--font-${slug(String(props.typography).replace(/[{}]/g, "").replace(/^typography\./, ""))}-weight) var(--font-${slug(String(props.typography).replace(/[{}]/g, "").replace(/^typography\./, ""))}-size) var(--font-${slug(String(props.typography).replace(/[{}]/g, "").replace(/^typography\./, ""))}-family);`);
    css.push(`}`);
  }
}
mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, css.join("\n") + "\n");
const nColors = Object.keys(root.colors || {}).length, nType = Object.keys(root.typography || {}).length;
console.log(`tokens-css: ${nColors} colors, ${nType} type roles, ${Object.keys(root.rounded || {}).length} radii, ${Object.keys(root.spacing || {}).length} spacing steps, ${comps.length} component recipes -> ${opt("--out", "design/tokens.css")}`);
if (!nColors) { console.error("no colors in frontmatter: DESIGN.md is a seed, not a design system"); process.exit(1); }
